spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/todo-dev
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret-key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000